import pandas as pd
df=pd.read_csv('train.csv')
type(df)
print("head of the data")
print(df.head())
print("Tail of the data")
print(df.tail())
print("description of the data")
print(df.describe())
print("To find missing values")
print(df.isnull().sum())
df=df.dropna()
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df['Category']=df['Category'].fillna("Unknown")
print(df.duplicated().sum())
df=df.drop_duplicates()
print(df.duplicated().sum())
print(df.dtypes)
df['Order Date']=pd.to_datetime(df['Order Date'], dayfirst=True)
print(df.dtypes)
df.info()
print(df.head())
df.to_csv('Cleaned_train.csv', index=False)